---
name: bake-ansible-images-v1
'on': workflow_call
jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      dist: ${{ steps.read-matrix.outputs.dist }}
    steps:
      - uses: actions/checkout@v3
      - name: read platform-matrix-v1.json
        id: read-matrix
        run: echo "dist=$(jq -cr '@json' < platform-matrix-v1.json)" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: [prepare-matrix]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: docker/bake-action@v4
        env:
          UPSTREAM_TAG: "0.0.0-${{ matrix.dist.OS }}.${{ matrix.dist.OS_VER }}"
          TARGET_SLUG: "${{ github.repository }}"
          TARGET_TAG: "0.0.0-${{ matrix.dist.OS }}.${{ matrix.dist.OS_VER }}"
          SHA: "${{ github.sha }}"
        with:
          pull: true
          push: true
          source: https://github.com/andrewrothstein/bake-ansible-images-v1.git#develop
      - uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: "ghcr.io/${{ github.repository }}:0.0.0-${{ matrix.distro.OS }}.${{ matrix.distro.OS_VER }}"
          severity: 'CRITICAL,HIGH'
          format: sarif
          output: trivy-results.sarif
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
    strategy:
      fail-fast: false
      matrix:
        dist: ${{ fromJSON(needs.prepare-matrix.outputs.dist) }}
